name: CI Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  DOTNET_VERSION: '8.0.x'
  CORE_PROJECT_PATH: 'src/CloudflareD1.NET/CloudflareD1.NET.csproj'
  LINQ_PROJECT_PATH: 'src/CloudflareD1.NET.Linq/CloudflareD1.NET.Linq.csproj'
  MIGRATIONS_PROJECT_PATH: 'src/CloudflareD1.NET.Migrations/CloudflareD1.NET.Migrations.csproj'
  CLI_PROJECT_PATH: 'tools/dotnet-d1/dotnet-d1.csproj'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
